---
pigen_chroot: false
pi_user: nick
pi_home: /home/nick

# Packages installed at system level (bootstrap only)
bootstrap_packages:
  - android-sdk-platform-tools
  - git
  - curl
  - jq

# udev vendor IDs for Android devices
android_usb_vendors:
  - "04e8"  # Samsung
  - "18d1"  # Google
