[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0

[program:xvfb]
command=Xvfb :%(ENV_DISPLAY_NUM)s -screen 0 %(ENV_DISPLAY_RESOLUTION)s
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:scrcpy]
command=scrcpy --max-fps %(ENV_SCRCPY_MAX_FPS)s -b %(ENV_SCRCPY_BITRATE)s --window-borderless --window-x 0 --window-y 0
environment=DISPLAY=":%(ENV_DISPLAY_NUM)s"
autorestart=true
startsecs=5
startretries=999
priority=20
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:x11vnc]
command=x11vnc -display :%(ENV_DISPLAY_NUM)s -nopw -forever -rfbport %(ENV_VNC_PORT)s -clip %(ENV_VNC_CLIP)s -scale %(ENV_VNC_SCALE)s
autorestart=true
startsecs=5
priority=30
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
