/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["performAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listApps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/running": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRunningApps"];
        put?: never;
        post: operations["launchApp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps/running/{package}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["stopApp"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clipboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getClipboard"];
        put: operations["setClipboard"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["searchContacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDeviceInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["dismissNotification"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{key}/action/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["triggerNotificationAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["openUri"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/record/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startRecording"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/record/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRecordingStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/record/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["stopRecording"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screenshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getScreenshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sms/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sendSms"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sms/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSmsThreads"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sms/threads/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSmsMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        A11yNode: {
            bounds?: null | components["schemas"]["Bounds"];
            checkable: boolean;
            checked: boolean;
            children: components["schemas"]["A11yNode"][];
            class: string;
            clickable: boolean;
            content_desc?: string | null;
            enabled: boolean;
            focusable: boolean;
            focused: boolean;
            long_clickable: boolean;
            ref_id?: string | null;
            resource_id?: string | null;
            scrollable: boolean;
            selected: boolean;
            text?: string | null;
        };
        Action: (components["schemas"]["TapParams"] & {
            /** @enum {string} */
            action: "tap";
        }) | (components["schemas"]["TapParams"] & {
            /** @enum {string} */
            action: "long_tap";
        }) | (components["schemas"]["SwipeParams"] & {
            /** @enum {string} */
            action: "swipe";
        }) | (components["schemas"]["PinchParams"] & {
            /** @enum {string} */
            action: "pinch";
        }) | (components["schemas"]["KeyParams"] & {
            /** @enum {string} */
            action: "key";
        }) | (components["schemas"]["TypeParams"] & {
            /** @enum {string} */
            action: "type";
        }) | (components["schemas"]["SetTextParams"] & {
            /** @enum {string} */
            action: "set_text";
        }) | (components["schemas"]["ScrollParams"] & {
            /** @enum {string} */
            action: "scroll_forward";
        }) | (components["schemas"]["ScrollParams"] & {
            /** @enum {string} */
            action: "scroll_backward";
        });
        App: {
            label?: string | null;
            package: string;
        };
        Bounds: {
            /** Format: int32 */
            x1: number;
            /** Format: int32 */
            x2: number;
            /** Format: int32 */
            y1: number;
            /** Format: int32 */
            y2: number;
        };
        /** @description Clipboard text content */
        ClipboardContent: {
            /** @description Current clipboard text (null if empty) */
            text?: string | null;
        };
        Contact: {
            name: string;
            phones: string[];
        };
        /** @description Device metadata and connection status */
        DeviceInfo: {
            /** @description Current foreground activity */
            activity?: string | null;
            /** @description Device owner app connected */
            bridge: boolean;
            model?: string | null;
            /** @description SIM phone number (e.g. "+15551234567") */
            phone_number?: string | null;
            /** @description e.g. "1080x2316" */
            resolution?: string | null;
            /** @description Snapshot server (app_process) connected */
            snapshot_server: boolean;
            window?: string | null;
        };
        ErrorResponse: {
            error: string;
        };
        KeyParams: {
            /** @description Key name (home, back, enter, power, etc.) or raw keycode number */
            key: string;
        };
        LaunchBody: {
            package: string;
        };
        /** @description Phone notification */
        Notification: {
            actions?: components["schemas"]["NotificationAction"][] | null;
            /** @description Unique notification key (use for dismiss/action) */
            key: string;
            package: string;
            text?: string | null;
            /**
             * Format: int64
             * @description Post time in milliseconds
             */
            time?: number | null;
            title?: string | null;
        };
        NotificationAction: {
            /**
             * Format: int32
             * @description Action index (use for triggering)
             */
            index: number;
            title: string;
        };
        OkResponse: {
            ok: boolean;
        };
        OpenBody: {
            uri: string;
        };
        PinchParams: {
            /**
             * Format: int32
             * @description Duration in ms (default 500)
             */
            duration_ms?: number;
            /**
             * Format: int32
             * @description Ending finger distance (larger = zoom in)
             */
            end_radius: number;
            /**
             * Format: int32
             * @description Starting finger distance from center
             */
            start_radius: number;
            /**
             * Format: int32
             * @description Center X
             */
            x: number;
            /**
             * Format: int32
             * @description Center Y
             */
            y: number;
        };
        RecordStatus: {
            /** Format: int32 */
            elapsed?: number | null;
            /** Format: int32 */
            max_duration?: number | null;
            recording: boolean;
        };
        ScrollParams: {
            /** @description Scrollable element ref ID */
            ref: string;
        };
        SendSmsBody: {
            body: string;
            to: string;
        };
        SetClipboardBody: {
            text: string;
        };
        SetTextParams: {
            /** @description Element ref ID (must be an EditText) */
            ref: string;
            /** @description Text to set (full Unicode support) */
            text: string;
        };
        SmsMessage: {
            address: string;
            body: string;
            date: string;
            /** Format: int64 */
            id: number;
            type: string;
        };
        SmsThread: {
            address: string;
            date: string;
            snippet: string;
            /** Format: int64 */
            thread_id: number;
        };
        StartRecordBody: {
            /**
             * Format: int32
             * @description Max recording duration in seconds (default 30, max 180)
             */
            max_duration?: number;
        };
        SwipeParams: {
            /**
             * Format: int32
             * @description Duration in ms (default 300)
             */
            duration_ms?: number;
            /** Format: int32 */
            x1: number;
            /** Format: int32 */
            x2: number;
            /** Format: int32 */
            y1: number;
            /** Format: int32 */
            y2: number;
        };
        TapParams: {
            /** @description Element ref ID (if tapping by ref, e.g. "e5") */
            ref?: string | null;
            /**
             * Format: int32
             * @description X coordinate (if tapping by position)
             */
            x?: number | null;
            /**
             * Format: int32
             * @description Y coordinate (if tapping by position)
             */
            y?: number | null;
        };
        TypeParams: {
            /** @description Text to type (ASCII only, via ADB input) */
            text: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    performAction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Action"];
            };
        };
        responses: {
            /** @description Action performed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Reference not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listApps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["App"][];
                };
            };
        };
    };
    listRunningApps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["App"][];
                };
            };
        };
    };
    launchApp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LaunchBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    stopApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    getClipboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current clipboard content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClipboardContent"];
                };
            };
        };
    };
    setClipboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetClipboardBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    searchContacts: {
        parameters: {
            query?: {
                /** @description Search query */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contact"][];
                };
            };
        };
    };
    getDeviceInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceInfo"];
                };
            };
        };
    };
    listNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of active notifications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"][];
                };
            };
        };
    };
    dismissNotification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Notification key */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    triggerNotificationAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Notification key */
                key: string;
                /** @description Action index */
                index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    openUri: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    startRecording: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRecordBody"];
            };
        };
        responses: {
            /** @description Recording started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Recording already in progress */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getRecordingStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordStatus"];
                };
            };
        };
    };
    stopRecording: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description MP4 video with audio */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "video/mp4": unknown;
                };
            };
            /** @description No active recording */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getScreenshot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PNG image of the current phone screen */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": unknown;
                };
            };
        };
    };
    sendSms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendSmsBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    listSmsThreads: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmsThread"][];
                };
            };
        };
    };
    getSmsMessages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmsMessage"][];
                };
            };
        };
    };
    getSnapshot: {
        parameters: {
            query?: {
                /** @description Output format: text or json */
                format?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accessibility tree */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
