/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/clients/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pending client registrations. */
        get: operations["list_pending_clients"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/clients/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a pending client registration. */
        post: operations["approve_client"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/clients/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject a pending client registration. */
        post: operations["reject_client"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/dongles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all dongles. */
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/dongles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Admin DELETE: forget a dongle from the registry.
         *     "Forget" semantics — if the dongle is still alive, the next heartbeat re-registers it.
         */
        delete: operations["admin_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query event log. */
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/hosts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all hosts. */
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/hosts/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pending host registrations. */
        get: operations["list_pending_hosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/hosts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single host by ID. */
        get: operations["get"];
        put?: never;
        post?: never;
        /**
         * Admin DELETE: forget a host from the registry.
         *     "Forget" semantics — if the host is still alive, the next heartbeat re-registers it.
         */
        delete: operations["admin_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/hosts/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a pending host registration. */
        post: operations["approve_host"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/hosts/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject a pending host registration. */
        post: operations["reject_host"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/phones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List phones (summary). */
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/phones/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Phone detail with host location, SIMs, and config. */
        get: operations["get_detail"];
        put?: never;
        post?: never;
        /**
         * Admin DELETE: forget a phone from the registry.
         *     "Forget" semantics — if the device is still alive, the next heartbeat re-registers it.
         */
        delete: operations["admin_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/phones/{id}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get phone config. */
        get: operations["get_config"];
        /** Set phone config (pushes to host). */
        put: operations["set_config"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/sims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all SIMs, optionally filtered by phone_number. */
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all tokens. */
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tokens/{id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke a token. */
        post: operations["revoke"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/poll/{pending_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Client long-polls for registration approval (public). */
        post: operations["poll_client"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Client requests registration (public, no auth). */
        post: operations["register_client"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hosts/dongles/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report dongles from a host (node-scope). */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hosts/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report an event from a host (node-scope). */
        post: operations["report"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hosts/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Heartbeat with host metadata and connected phones/dongles. */
        post: operations["heartbeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hosts/phones/deregister": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a phone as disconnected (node-scope). */
        post: operations["deregister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hosts/phones/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register or update a phone (node-scope). */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hosts/phones/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Permanently remove a phone (Pi-initiated, node-scope). */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hosts/phones/{phone_id}/sims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report SIM inventory for a phone (node-scope). */
        post: operations["report"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hosts/poll/{pending_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Host long-polls for registration approval (public). */
        post: operations["poll_host"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hosts/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Host requests registration (public, no auth). */
        post: operations["register_host"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        AuthScope: "node" | "admin";
        DeregisterPhoneBody: {
            host_id: string;
            phone_id: string;
        };
        Dongle: {
            bt_mac: string;
            /** Format: date-time */
            created_at: string;
            hci_device?: string | null;
            host_id?: string | null;
            id: string;
            phone_id?: string | null;
            status: string;
        };
        DongleEntry: {
            bt_mac: string;
            hci_device?: string | null;
            phone_id?: string | null;
        };
        Event: {
            data?: unknown;
            entity_id?: string | null;
            event_type: string;
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            timestamp: string;
        };
        HeartbeatBody: {
            /** Format: int32 */
            api_port?: number;
            dongles?: string[];
            fqdn?: string | null;
            host_id: string;
            phones?: string[];
            tailscale_ip?: string | null;
        };
        Host: {
            /** Format: int32 */
            api_port: number;
            /** Format: date-time */
            created_at: string;
            fqdn?: string | null;
            id: string;
            /** Format: date-time */
            last_heartbeat?: string | null;
            status: string;
            tailscale_ip?: string | null;
        };
        PendingRegistration: {
            /** @description For host registrations this is the host_id; for client registrations a label. */
            host_id: string;
            hostname?: string | null;
            id: string;
            kind?: components["schemas"]["RegistrationKind"];
            /**
             * @description Raw token stashed here temporarily after approval so the polling process can read it.
             *     Cleared after the first successful poll retrieval.
             */
            raw_token?: string | null;
            /** Format: date-time */
            requested_at: string;
            /** Format: date-time */
            resolved_at?: string | null;
            status: components["schemas"]["RegistrationStatus"];
            tailnet_node_id?: string | null;
            token_id?: string | null;
        };
        Phone: {
            adapter_mac?: string | null;
            adb_serial: string;
            bt_mac?: string | null;
            config: components["schemas"]["PhoneConfig"];
            /** Format: date-time */
            connected_at?: string | null;
            /** Format: date-time */
            created_at: string;
            host_id?: string | null;
            id: string;
            imei?: string | null;
            model?: string | null;
            phone_number?: string | null;
            status: string;
            /** Format: date-time */
            updated_at: string;
        };
        PhoneConfig: {
            bluetooth_enabled: boolean;
            wifi_enabled: boolean;
        };
        RegisterClientBody: {
            client_id: string;
            hostname?: string | null;
        };
        RegisterDonglesBody: {
            dongles: components["schemas"]["DongleEntry"][];
            host_id: string;
        };
        RegisterHostBody: {
            host_id: string;
            hostname?: string | null;
            tailnet_node_id?: string | null;
        };
        RegisterPhoneBody: {
            adapter_mac?: string | null;
            adb_serial: string;
            bt_mac?: string | null;
            host_id: string;
            imei?: string | null;
            model?: string | null;
            phone_number?: string | null;
        };
        /** @enum {string} */
        RegistrationKind: "host" | "client";
        /** @enum {string} */
        RegistrationStatus: "pending" | "approved" | "rejected";
        ReportEventBody: {
            category: string;
            data?: unknown;
            host_id?: string | null;
            message: string;
            phone_id?: string | null;
            severity: string;
        };
        ReportSimsBody: {
            sims: components["schemas"]["SimEntry"][];
        };
        SimCard: {
            carrier?: string | null;
            /** Format: date-time */
            created_at: string;
            iccid: string;
            id: string;
            is_active: boolean;
            is_esim: boolean;
            phone_id: string;
            phone_number?: string | null;
            profile_name?: string | null;
            /** Format: int32 */
            slot: number;
            /** Format: date-time */
            updated_at: string;
        };
        SimEntry: {
            carrier?: string | null;
            iccid: string;
            is_active: boolean;
            is_esim: boolean;
            phone_number?: string | null;
            profile_name?: string | null;
            /** Format: int32 */
            slot: number;
        };
        Token: {
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            expires_at?: string | null;
            id: string;
            /** Format: date-time */
            last_seen_at?: string | null;
            /** @description For node tokens, the host_id this token is bound to. */
            node_id?: string | null;
            note?: string | null;
            /** Format: date-time */
            revoked_at?: string | null;
            scope: components["schemas"]["AuthScope"];
            /** @description SHA-256 hex hash of the raw token. */
            token_hash: string;
            /** @description First 12 chars of the raw token, for display in admin UI. */
            token_prefix: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_pending_clients: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pending client registrations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingRegistration"][];
                };
            };
        };
    };
    approve_client: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Registration ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Approved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Registration not found or already resolved */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reject_client: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Registration ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rejected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Registration not found or already resolved */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All dongles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dongle"][];
                };
            };
        };
    };
    admin_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Dongle ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dongle forgotten */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Dongle not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: {
                event_type?: string | null;
                entity_id?: string | null;
                phone_id?: string | null;
                severity?: string | null;
                category?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Filtered events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All hosts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Host"][];
                };
            };
        };
    };
    list_pending_hosts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pending host registrations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingRegistration"][];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Host ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Host details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Host"];
                };
            };
            /** @description Host not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Host ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Host forgotten */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Host not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    approve_host: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Registration ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Approved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Registration not found or already resolved */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reject_host: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Registration ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rejected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Registration not found or already resolved */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All phones */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Phone"][];
                };
            };
        };
    };
    get_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Phone ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Phone detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Phone not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Phone ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Phone forgotten */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Phone not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_config: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Phone ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Phone config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhoneConfig"];
                };
            };
            /** @description Phone not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    set_config: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Phone ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhoneConfig"];
            };
        };
        responses: {
            /** @description Config updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Phone not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: {
                phone_number?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All SIMs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimCard"][];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All tokens */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"][];
                };
            };
        };
    };
    revoke: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Token ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Token not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    poll_client: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pending registration ID */
                pending_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Approved — token returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Registration rejected */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Poll timeout — retry */
            408: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register_client: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterClientBody"];
            };
        };
        responses: {
            /** @description Registration pending */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDonglesBody"];
            };
        };
        responses: {
            /** @description Dongles registered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    report: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportEventBody"];
            };
        };
        responses: {
            /** @description Event recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    heartbeat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeartbeatBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    deregister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeregisterPhoneBody"];
            };
        };
        responses: {
            /** @description Phone deregistered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterPhoneBody"];
            };
        };
        responses: {
            /** @description Phone registered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Phone ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Phone deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Phone not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    report: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Phone ID */
                phone_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportSimsBody"];
            };
        };
        responses: {
            /** @description SIMs updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    poll_host: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pending registration ID */
                pending_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Approved — token returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Registration rejected */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Poll timeout — retry */
            408: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register_host: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterHostBody"];
            };
        };
        responses: {
            /** @description Registration pending */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
